### PR TITLE
Make the wallet compile in ubuntu 17.10 etc

### PR DESCRIPTION
**Pull request by kimusan**
The code has not been kept up to date with latest updates to toolchain,
so it did not compile on Ubuntu 17.10 and similar.
This patch makes it compile again.

### CODE REVIEW

**Comment by skeincoin** [comment]
The #include <QtWidgets/ changes breaks compatibility with Qt4.

It should be possible to modify the make files to work for both Qt4 and Qt5 as in Bitcoin 0.14.

**Comment by kimusan** [comment]
Yes agree, but it seems like the entire QT_INCLUDES part of the autoconfigure scripts are not taken into consideration at all - this was the quickfix (do people really still use QT4?)

**Comment by kimusan** [comment]
I will make a fix and resubmit asap

**Comment by kimusan** [comment]
Should be better now.

**Comment by skeincoin** [comment]
Yes, can confirm it compiles with Qt4.

Thanks!

**Pull request merged**
